USE CSE_3A_164

CREATE TABLE SALES_DATA(
REGION VARCHAR(30),
PRODUCT VARCHAR(15),
SALES_AMOUNT INT,
[YEAR] INT
);

INSERT INTO SALES_DATA
VALUES ('North America', 'Watch', 1500, 2023), 
('Europe', 'Mobile', 1200, 2023), 
('Asia', 'Watch', 1800, 2023), 
('North America', 'TV', 900, 2024), 
('Europe', 'Watch', 2000, 2024), 
('Asia', 'Mobile', 1000, 2024), 
('North America', 'Mobile', 1600, 2023), 
('Europe', 'TV', 1500, 2023), 
('Asia', 'TV', 1100, 2024), 
('North America', 'Watch', 1700, 2024); 

SELECT * FROM SALES_DATA

---Display Total Sales Amount by Region. 
SELECT REGION,SUM(SALES_AMOUNT) AS TOTAL
FROM SALES_DATA
GROUP BY REGION

---Display Average Sales Amount by Product 
SELECT PRODUCT,AVG(SALES_AMOUNT) AS AVG
FROM SALES_DATA
GROUP BY PRODUCT

----Display Maximum Sales Amount by Year 

SELECT [YEAR],MAX(SALES_AMOUNT) AS [MAX]
FROM SALES_DATA
GROUP BY [YEAR]

----Display Minimum Sales Amount by Region and Year 

SELECT REGION,[YEAR],MIN(SALES_AMOUNT) AS [MIN]
FROM SALES_DATA
GROUP BY REGION,[YEAR] 

---Count of Products Sold by Region 

SELECT REGION,COUNT(PRODUCT) AS [COUNT]
FROM SALES_DATA
GROUP BY REGION

---Display Sales Amount by Year and Product

SELECT [YEAR],PRODUCT,SUM(SALES_AMOUNT) AS SALES_AMOUNT
FROM SALES_DATA
GROUP BY [YEAR],PRODUCT 

---Display Regions with Total Sales Greater Than 5000 

SELECT REGION, SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM SALES_DATA
GROUP BY REGION
HAVING SUM(SALES_AMOUNT)>5000

----Display Products with Average Sales Less Than 10000

SELECT PRODUCT, AVG(SALES_AMOUNT) AS [AVG_SALES]
FROM SALES_DATA
GROUP BY PRODUCT
HAVING AVG(SALES_AMOUNT)<10000

---Display Years with Maximum Sales Exceeding 500 

SELECT [YEAR],MAX(SALES_AMOUNT) AS [MAX_SALES]
FROM SALES_DATA
GROUP BY [YEAR]
HAVING MAX(SALES_AMOUNT)>500

---Display Regions with at Least 3 Distinct Products Sold.

SELECT REGION, COUNT(DISTINCT PRODUCT) AS [COUNT]
FROM SALES_DATA
GROUP BY REGION
HAVING COUNT(DISTINCT PRODUCT) >= 3


---- Display Years with Minimum Sales Less Than 1000

SELECT [YEAR], MIN(SALES_AMOUNT) AS [MIN]
FROM SALES_DATA
GROUP BY [YEAR]
HAVING MIN(SALES_AMOUNT)<1000

----Display Total Sales Amount by Region for Year 2023, Sorted by Total Amount

SELECT REGION,SUM(SALES_AMOUNT) AS [TOTAL_SALES]
FROM SALES_DATA
WHERE YEAR=2023
GROUP BY REGION
ORDER BY TOTAL_SALES

---- Find the Region Where 'Mobile' Had the Lowest Total Sales Across All Years. 

SELECT TOP 1 REGION,SUM(SALES_AMOUNT) AS [TOTAL_SALES]
FROM SALES_DATA
WHERE PRODUCT='MOBILE'
GROUP BY REGION
ORDER BY TOTAL_SALES

----Find the Product with the Highest Sales Across All Regions in 2023. 

SELECT TOP 1 PRODUCT, SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM SALES_DATA
GROUP BY PRODUCT
ORDER BY TOTAL_SALES DESC

---Find Regions Where 'TV' Sales in 2023 Were Greater Than 1000. 

SELECT REGION, SUM(SALES_AMOUNT) AS [TOTAL_SALES]
FROM SALES_DATA
WHERE PRODUCT='TV' AND YEAR=2023
GROUP BY REGION
HAVING SUM(SALES_AMOUNT)>1000


---PART-B----

----Display Count of Orders by Year and Region, Sorted by Year and Region

SELECT [YEAR],REGION,COUNT(PRODUCT) AS ORDER_COUNT
FROM SALES_DATA
GROUP BY [YEAR],REGION
ORDER BY [YEAR],REGION

----Display Regions with Maximum Sales Amount Exceeding 1000 in Any Year, Sorted by Region 

SELECT REGION,MAX(SALES_AMOUNT) AS [MAX]
FROM SALES_DATA
GROUP BY REGION
HAVING MAX(SALES_AMOUNT)>1000

----Display Years with Total Sales Amount Less Than 10000, Sorted by Year Descending 

SELECT [YEAR], SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM SALES_DATA
GROUP BY [YEAR]
HAVING SUM(SALES_AMOUNT)<10000
ORDER BY [YEAR] DESC

----Display Top 3 Regions by Total Sales Amount in Year 2024 

SELECT TOP 3 REGION, SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM SALES_DATA
WHERE [YEAR]=2024
GROUP BY REGION

----Find the Year with the Lowest Total Sales Across All Regions. 

SELECT TOP 1 [YEAR], MIN(SALES_AMOUNT) AS LOWEST_SALES
FROM SALES_DATA
GROUP BY [YEAR]

----PART-C-----

----Display Products with Average Sales Amount Between 1000 and 2000, Ordered by Product Name 

SELECT PRODUCT, AVG(SALES_AMOUNT) AS [AVG]
FROM SALES_DATA
GROUP BY PRODUCT
HAVING AVG(SALES_AMOUNT) BETWEEN 1000 AND 2000
ORDER BY PRODUCT 

----Display Years with More Than 1 Orders from Each Region 

SELECT [YEAR],REGION, COUNT(PRODUCT) AS [ORDER_COUNT]
FROM SALES_DATA
GROUP BY [YEAR],REGION
HAVING COUNT(PRODUCT)>1

----Display Regions with Average Sales Amount Above 1500 in Year 2023 sort by AVERAGE amount in descending. (IMPPPPPPPP)

SELECT REGION, AVG(SALES_AMOUNT) AS [AVG]
FROM SALES_DATA
WHERE [YEAR]=2023
GROUP BY REGION
HAVING AVG(SALES_AMOUNT)>1500
ORDER BY [AVG] DESC

----Find out region wise duplicate product.(IMPPPPPPP) 

SELECT REGION,PRODUCT, COUNT( PRODUCT) AS COUNT_
FROM SALES_DATA
GROUP BY REGION,PRODUCT
HAVING COUNT(PRODUCT)>1


-----Find out year wise duplicate product.(IMPPPPP)
SELECT [YEAR],PRODUCT, COUNT( PRODUCT) AS COUNT_
FROM SALES_DATA
GROUP BY [YEAR],PRODUCT
HAVING COUNT(PRODUCT)>1





