CREATE TABLE STU_MASTER(
	RNO INT PRIMARY KEY ,
	NAME VARCHAR(100),
	BRANCH varchar(10) DEFAULT ('GENERAL'),
	SPI DECIMAL(8,2) CHECK (SPI<=10),
	BKLOG INT CHECK (BKLOG>=0)
);


INSERT INTO STU_MASTER VALUES
(101, 'Raju', 'CE', 8.80, 0),
(102, 'Amit', 'CE', 2.20, 3),
(103, 'Sanjay', 'ME', 1.50, 6),
(104, 'Neha', 'EC', 7.65, 0),
(105, 'Meera', 'EE', 5.52, 2),
(106, 'Mahesh',NULL,4.50, 3)

UPDATE STU_MASTER
SET SPI=12
WHERE NAME='RAJU'

UPDATE STU_MASTER
SET BKLOG=-1
WHERE NAME='NEHA'

CREATE TABLE DEPT_DETAILS(
DID INT PRIMARY KEY,
DNAME VARCHAR(10)
);

CREATE TABLE CITY_DETAILS(
CID INT PRIMARY KEY,
CNAME VARCHAR(10)
);

CREATE TABLE EMP_DETAILS(
EID INT PRIMARY KEY,
ENAME VARCHAR(100),
DID INT FOREIGN KEY REFERENCES DEPT_DETAILS(DID),
CID INT FOREIGN KEY REFERENCES CITY_DETAILS(CID),
SALARY DECIMAL(8,2) CHECK (SALARY>=0),
EXPERIENCE INT CHECK(EXPERIENCE>=0)
);








	







